### ISSUE TITLE
Package masks acf from base R.

### ISSUE THREAD

**Issue by rkillick** [rkillick/changepoint.online#3]
library("changepoint.online")
set.seed(1)
m1=c(rnorm(100,0,1),rnorm(100,5,1))
acf(m1)

Should correctly plot the acf of the m1 time series but instead errors:

> Error in (function (classes, fdef, mtable)  : 
> unable to find an inherited method for function ‘acf’ for signature ‘"numeric"

**Comment by AndrewC1998** [comment]
This issue has been fixed in the latest push. The error was coming about from an artefact of the changepoint package code that is no longer used.
